import Link from 'next/link'
import Image from 'next/image'
import { LeadAssistant } from './LeadAssistant'

export interface ResourceSection { title: string; paragraphs: string[]; points?: string[] }
export interface ResourceContent { slug: string; category: string; title: string; description: string; image: string; imageAlt: string; readingTime: string; updated: string; sections: ResourceSection[]; relatedService: { label: string; href: string } }

export function ResourceArticle({ content }: { content: ResourceContent }) {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://momentundigital.com'
  const schema = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Article', headline: content.title, description: content.description, image: `${siteUrl}${content.image}`, dateModified: content.updated, datePublished: content.updated, inLanguage: 'es-ES', author: { '@type': 'Organization', name: 'MOMENTUNDIGITAL', url: siteUrl }, publisher: { '@type': 'Organization', name: 'MOMENTUNDIGITAL', url: siteUrl }, mainEntityOfPage: `${siteUrl}/recursos/${content.slug}` },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Inicio', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Recursos', item: `${siteUrl}/recursos` }, { '@type': 'ListItem', position: 3, name: content.title, item: `${siteUrl}/recursos/${content.slug}` }] },
  ] }
  return <main className="resource-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} /><header className="service-nav"><Link href="/" className="factory-logo"><span className="factory-mark">MD</span><span>MOMENTUNDIGITAL</span></Link><Link href="/recursos" className="service-nav-cta">Todos los recursos <span>↗</span></Link></header><article><header className="resource-hero"><div className="service-breadcrumb"><Link href="/">Inicio</Link><span>/</span><Link href="/recursos">Recursos</Link></div><p>{content.category}</p><h1>{content.title}</h1><div><span>Por el equipo de MOMENTUNDIGITAL</span><span>{content.readingTime}</span><span>Actualizado {content.updated.split('-').reverse().join('/')}</span></div><strong>{content.description}</strong></header><figure className="resource-cover"><Image src={content.image} alt={content.imageAlt} fill sizes="(max-width: 900px) 100vw, 1220px" /></figure><div className="resource-body"><aside><span>En esta guía</span>{content.sections.map((section, index) => <a key={section.title} href={`#seccion-${index + 1}`}>{String(index + 1).padStart(2, '0')} {section.title}</a>)}</aside><div>{content.sections.map((section, index) => <section id={`seccion-${index + 1}`} key={section.title}><small>{String(index + 1).padStart(2, '0')}</small><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.points && <ul>{section.points.map((point) => <li key={point}>{point}</li>)}</ul>}</section>)}</div></div><aside className="resource-cta"><p>Del análisis a una decisión concreta</p><h2>¿Quieres aplicarlo a tu proyecto?</h2><span>Revisamos contigo el alcance, los riesgos y el siguiente paso más sensato.</span><Link href="/#diagnostico" className="factory-button">Solicitar diagnóstico <b>↗</b></Link><Link href={content.relatedService.href}>{content.relatedService.label}</Link></aside></article><footer className="service-footer"><Link href="/">MOMENTUNDIGITAL</Link><a href="mailto:contacto@momentundigital.com">contacto@momentundigital.com</a><Link href="/privacidad">Privacidad</Link></footer><LeadAssistant /></main>
}
