import type { ResourceContent } from '@/components/marketing/ResourceArticle'

export const resourceContent: Record<string, ResourceContent> = {
  'guia-desarrollo-saas': { slug: 'guia-desarrollo-saas', category: 'Guía de decisión', title: 'Cómo plantear un SaaS a medida sin empezar por la tecnología', description: 'Una guía para ordenar problema, usuario, alcance, costes y riesgos antes de contratar el desarrollo de un producto SaaS.', image: '/images/resource-saas-planning.png', imageAlt: 'Sistema modular de metal y acrílico dispuesto sobre un plano de trabajo', readingTime: '8 min de lectura', updated: '2026-09-01', relatedService: { label: 'Ver desarrollo SaaS a medida', href: '/desarrollo-saas' }, sections: [
    { title: 'Empieza por el cambio de comportamiento', paragraphs: ['Un producto SaaS no empieza con una lista de funciones. Empieza con una tarea que una persona necesita completar mejor que hoy.', 'Antes de elegir tecnología, describe quién utilizará el producto, qué intenta conseguir, qué alternativa utiliza ahora y por qué cambiaría. Si esa respuesta no es clara, el desarrollo solo hará más cara la incertidumbre.'], points: ['Usuario concreto y contexto de uso', 'Tarea principal que debe completar', 'Alternativa actual y coste del problema', 'Motivo real para adoptar una solución nueva'] },
    { title: 'Diferencia producto, operación y administración', paragraphs: ['La interfaz del cliente es solo una parte. También hay que operar cuentas, resolver incidencias, gestionar permisos y entender qué ocurre dentro del sistema.', 'Separar estas tres capas evita descubrir demasiado tarde que el producto funciona para una demo, pero no para prestar el servicio cada día.'], points: ['Experiencia del usuario final', 'Herramientas del equipo que opera el servicio', 'Administración, soporte y trazabilidad'] },
    { title: 'Recorta el alcance con una prueba', paragraphs: ['Cada función debe justificar qué riesgo reduce o qué aprendizaje permite. Si no cambia una decisión, probablemente puede esperar.', 'Un primer alcance sólido completa un recorrido importante de principio a fin. No necesita cubrir todos los casos, pero sí debe ser utilizable sin intervención constante del equipo fundador.'] },
    { title: 'Calcula el coste completo', paragraphs: ['El presupuesto no termina con la primera versión. Incluye alojamiento, servicios externos, soporte, seguridad, analítica y evolución.', 'Pide que la propuesta diferencie construcción inicial, costes recurrentes y supuestos. Así podrás comparar opciones sin elegir una cifra que después se multiplica.'], points: ['Diseño y desarrollo inicial', 'Infraestructura y proveedores', 'Mantenimiento y soporte', 'Nuevas iteraciones', 'Migración o carga de datos'] },
    { title: 'Señales de una propuesta responsable', paragraphs: ['Una buena propuesta explica qué queda fuera, qué decisiones siguen abiertas y cómo se validará el resultado. Desconfía de calendarios cerrados antes de entender usuarios, datos e integraciones.', 'El objetivo no es contratar el mayor alcance. Es reducir el riesgo suficiente para tomar la siguiente decisión con información real.'] },
  ] },
  'automatizacion-ia-empresa': { slug: 'automatizacion-ia-empresa', category: 'Automatización aplicada', title: 'Qué procesos merece la pena automatizar con IA y cuáles no', description: 'Un criterio práctico para elegir casos de automatización con impacto, datos suficientes y un nivel de riesgo controlable.', image: '/images/resource-ai-automation.png', imageAlt: 'Proceso mecánico que ordena documentos mediante un módulo rojo translúcido', readingTime: '7 min de lectura', updated: '2026-09-01', relatedService: { label: 'Ver automatización con IA', href: '/automatizacion-ia' }, sections: [
    { title: 'Busca frecuencia antes que espectacularidad', paragraphs: ['El mejor primer caso no suele ser el más llamativo. Suele ser una tarea repetida muchas veces, con entradas parecidas y un resultado que alguien puede revisar.', 'Ahorrar pocos minutos en un proceso diario puede aportar más que automatizar una decisión excepcional y arriesgada.'], points: ['Alta frecuencia', 'Tiempo manual medible', 'Entradas disponibles', 'Resultado verificable'] },
    { title: 'Separa reglas de interpretación', paragraphs: ['Las reglas deterministas deben seguir siendo reglas. La IA aporta valor cuando hay que interpretar lenguaje, clasificar contenido, extraer información o proponer una respuesta.', 'Mezclar ambos tipos de decisión dentro de un modelo dificulta explicar errores y controlar el comportamiento.'] },
    { title: 'Diseña la revisión humana', paragraphs: ['Revisión humana no significa revisar todo para siempre. Puede activarse por nivel de confianza, importe, tipo de documento o excepción.', 'El sistema debe mostrar qué información utilizó, permitir corregir el resultado y registrar esa corrección para mejorar el proceso.'], points: ['Umbrales de confianza', 'Casos que siempre requieren aprobación', 'Registro de cambios', 'Procedimiento ante error'] },
    { title: 'Prueba con datos representativos', paragraphs: ['Una demostración con ejemplos perfectos no valida una automatización. La prueba debe incluir formatos incompletos, lenguaje ambiguo y excepciones reales.', 'Define por adelantado precisión mínima, tiempo máximo, coste por operación y errores que no son aceptables.'] },
    { title: 'Mide el resultado operativo', paragraphs: ['La métrica no es cuántas llamadas hace el modelo. Mide tiempo ahorrado, retrabajo, errores, tiempo de respuesta y adopción del equipo.', 'Si el proceso no mejora después de incluir revisión y excepciones, automatizarlo no ha creado valor.'] },
  ] },
  'como-definir-mvp': { slug: 'como-definir-mvp', category: 'Producto y validación', title: 'Cómo definir el alcance de un MVP sin convertirlo en una demo inútil', description: 'Un método para decidir qué debe incluir la primera versión, qué debe quedar fuera y cómo saber si el lanzamiento ha funcionado.', image: '/images/resource-mvp-scope.png', imageAlt: 'Prototipo compacto rodeado de piezas descartadas sobre una mesa de trabajo', readingTime: '6 min de lectura', updated: '2026-09-01', relatedService: { label: 'Ver desarrollo de MVP', href: '/desarrollo-mvp' }, sections: [
    { title: 'Escribe la hipótesis que quieres probar', paragraphs: ['Un MVP existe para reducir una incertidumbre. Puede ser adopción, disposición a pagar, viabilidad operativa o capacidad técnica.', 'Si intentas demostrar todas a la vez, el alcance crecerá sin darte una respuesta clara. Elige la decisión que tomarás después del lanzamiento.'] },
    { title: 'Define un recorrido completo', paragraphs: ['La primera versión debe permitir que una persona complete la tarea principal y que el equipo pueda prestar el servicio detrás.', 'Una colección de pantallas sin operación, soporte ni datos reales puede servir para enseñar una idea, pero no para validarla.'], points: ['Entrada o registro', 'Tarea principal', 'Resultado reconocible', 'Operación y soporte básico', 'Medición del comportamiento'] },
    { title: 'Usa reglas para decir que no', paragraphs: ['Una función entra si es necesaria para completar el recorrido, reducir un riesgo crítico o medir la hipótesis. Todo lo demás va a una lista posterior.', 'No priorices por quién pide más fuerte. Prioriza por la evidencia que necesitas obtener.'] },
    { title: 'No confundas rapidez con deuda', paragraphs: ['Construir menos permite mantener calidad en autenticación, datos y despliegue. Recortar esos fundamentos puede acelerar una demo, pero retrasa el producto.', 'La arquitectura debe ser proporcional: suficiente para evolucionar, sin anticipar una escala que todavía no existe.'] },
    { title: 'Decide antes cómo medirás', paragraphs: ['Define eventos, entrevistas y umbrales antes de lanzar. Si eliges las métricas después, es fácil justificar cualquier resultado.', 'Una validación negativa también aporta valor si permite detener o cambiar la inversión a tiempo.'] },
  ] },
}
