import type { ResourceContent } from '@/components/marketing/ResourceArticle'

export const resourceContent: Record<string, ResourceContent> = {
  'guia-desarrollo-saas': { slug: 'guia-desarrollo-saas', category: 'Guía de decisión', title: 'Cómo plantear un SaaS a medida sin empezar por la tecnología', description: 'Una guía para ordenar problema, usuario, alcance, costes y riesgos antes de contratar el desarrollo de un producto SaaS.', image: '/images/resource-saas-planning.png', imageAlt: 'Sistema modular de metal y acrílico dispuesto sobre un plano de trabajo', readingTime: '8 min de lectura', updated: '2026-09-01', relatedService: { label: 'Ver desarrollo SaaS a medida', href: '/desarrollo-saas' }, sections: [
    { title: 'Empieza por el cambio de comportamiento', paragraphs: ['Un producto SaaS no empieza con una lista de funciones. Empieza con una tarea que una persona necesita completar mejor que hoy.', 'Antes de elegir tecnología, describe quién utilizará el producto, qué intenta conseguir, qué alternativa utiliza ahora y por qué cambiaría. Si esa respuesta no es clara, el desarrollo solo hará más cara la incertidumbre.'], points: ['Usuario concreto y contexto de uso', 'Tarea principal que debe completar', 'Alternativa actual y coste del problema', 'Motivo real para adoptar una solución nueva'] },
    { title: 'Diferencia producto, operación y administración', paragraphs: ['La interfaz del cliente es solo una parte. También hay que operar cuentas, resolver incidencias, gestionar permisos y entender qué ocurre dentro del sistema.', 'Separar estas tres capas evita descubrir demasiado tarde que el producto funciona para una demo, pero no para prestar el servicio cada día.'], points: ['Experiencia del usuario final', 'Herramientas del equipo que opera el servicio', 'Administración, soporte y trazabilidad'] },
    { title: 'Recorta el alcance con una prueba', paragraphs: ['Cada función debe justificar qué riesgo reduce o qué aprendizaje permite. Si no cambia una decisión, probablemente puede esperar.', 'Un primer alcance sólido completa un recorrido importante de principio a fin. No necesita cubrir todos los casos, pero sí debe ser utilizable sin intervención constante del equipo fundador.'] },
    { title: 'Calcula el coste completo', paragraphs: ['El presupuesto no termina con la primera versión. Incluye alojamiento, servicios externos, soporte, seguridad, analítica y evolución.', 'Pide que la propuesta diferencie construcción inicial, costes recurrentes y supuestos. Así podrás comparar opciones sin elegir una cifra que después se multiplica.'], points: ['Diseño y desarrollo inicial', 'Infraestructura y proveedores', 'Mantenimiento y soporte', 'Nuevas iteraciones', 'Migración o carga de datos'] },
    { title: 'Señales de una propuesta responsable', paragraphs: ['Una buena propuesta explica qué queda fuera, qué decisiones siguen abiertas y cómo se validará el resultado. Desconfía de calendarios cerrados antes de entender usuarios, datos e integraciones.', 'El objetivo no es contratar el mayor alcance. Es reducir el riesgo suficiente para tomar la siguiente decisión con información real.'] },
  ] },
  'automatizacion-ia-empresa': { slug: 'automatizacion-ia-empresa', category: 'Automatización aplicada', title: 'Qué procesos merece la pena automatizar con IA y cuáles no', description: 'Un criterio práctico para elegir casos de automatización con impacto, datos suficientes y un nivel de riesgo controlable.', image: '/images/resource-ai-automation.png', imageAlt: 'Proceso mecánico que ordena documentos mediante un módulo rojo translúcido', readingTime: '7 min de lectura', updated: '2026-09-01', relatedService: { label: 'Ver automatización con IA', href: '/automatizacion-ia' }, sections: [
    { title: 'Busca frecuencia antes que espectacularidad', paragraphs: ['El mejor primer caso no suele ser el más llamativo. Suele ser una tarea repetida muchas veces, con entradas parecidas y un resultado que alguien puede revisar.', 'Ahorrar pocos minutos en un proceso diario puede aportar más que automatizar una decisión excepcional y arriesgada.'], points: ['Alta frecuencia', 'Tiempo manual medible', 'Entradas disponibles', 'Resultado verificable'] },
    { title: 'Separa reglas de interpretación', paragraphs: ['Las reglas deterministas deben seguir siendo reglas. La IA aporta valor cuando hay que interpretar lenguaje, clasificar contenido, extraer información o proponer una respuesta.', 'Mezclar ambos tipos de decisión dentro de un modelo dificulta explicar errores y controlar el comportamiento.'] },
    { title: 'Diseña la revisión humana', paragraphs: ['Revisión humana no significa revisar todo para siempre. Puede activarse por nivel de confianza, importe, tipo de documento o excepción.', 'El sistema debe mostrar qué información utilizó, permitir corregir el resultado y registrar esa corrección para mejorar el proceso.'], points: ['Umbrales de confianza', 'Casos que siempre requieren aprobación', 'Registro de cambios', 'Procedimiento ante error'] },
    { title: 'Prueba con datos representativos', paragraphs: ['Una demostración con ejemplos perfectos no valida una automatización. La prueba debe incluir formatos incompletos, lenguaje ambiguo y excepciones reales.', 'Define por adelantado precisión mínima, tiempo máximo, coste por operación y errores que no son aceptables.'] },
    { title: 'Mide el resultado operativo', paragraphs: ['La métrica no es cuántas llamadas hace el modelo. Mide tiempo ahorrado, retrabajo, errores, tiempo de respuesta y adopción del equipo.', 'Si el proceso no mejora después de incluir revisión y excepciones, automatizarlo no ha creado valor.'] },
  ] },
  'como-definir-mvp': { slug: 'como-definir-mvp', category: 'Producto y validación', title: 'Cómo definir el alcance de un MVP sin convertirlo en una demo inútil', description: 'Un método para decidir qué debe incluir la primera versión, qué debe quedar fuera y cómo saber si el lanzamiento ha funcionado.', image: '/images/resource-mvp-scope.png', imageAlt: 'Prototipo compacto rodeado de piezas descartadas sobre una mesa de trabajo', readingTime: '6 min de lectura', updated: '2026-09-01', relatedService: { label: 'Ver desarrollo de MVP', href: '/desarrollo-mvp' }, sections: [
    { title: 'Escribe la hipótesis que quieres probar', paragraphs: ['Un MVP existe para reducir una incertidumbre. Puede ser adopción, disposición a pagar, viabilidad operativa o capacidad técnica.', 'Si intentas demostrar todas a la vez, el alcance crecerá sin darte una respuesta clara. Elige la decisión que tomarás después del lanzamiento.'] },
    { title: 'Define un recorrido completo', paragraphs: ['La primera versión debe permitir que una persona complete la tarea principal y que el equipo pueda prestar el servicio detrás.', 'Una colección de pantallas sin operación, soporte ni datos reales puede servir para enseñar una idea, pero no para validarla.'], points: ['Entrada o registro', 'Tarea principal', 'Resultado reconocible', 'Operación y soporte básico', 'Medición del comportamiento'] },
    { title: 'Usa reglas para decir que no', paragraphs: ['Una función entra si es necesaria para completar el recorrido, reducir un riesgo crítico o medir la hipótesis. Todo lo demás va a una lista posterior.', 'No priorices por quién pide más fuerte. Prioriza por la evidencia que necesitas obtener.'] },
    { title: 'No confundas rapidez con deuda', paragraphs: ['Construir menos permite mantener calidad en autenticación, datos y despliegue. Recortar esos fundamentos puede acelerar una demo, pero retrasa el producto.', 'La arquitectura debe ser proporcional: suficiente para evolucionar, sin anticipar una escala que todavía no existe.'] },
    { title: 'Decide antes cómo medirás', paragraphs: ['Define eventos, entrevistas y umbrales antes de lanzar. Si eliges las métricas después, es fácil justificar cualquier resultado.', 'Una validación negativa también aporta valor si permite detener o cambiar la inversión a tiempo.'] },
  ] },
  'cuanto-cuesta-desarrollar-saas': { slug: 'cuanto-cuesta-desarrollar-saas', category: 'Coste y planificación', title: 'Cuánto cuesta desarrollar un SaaS: partidas, alcance y costes ocultos', description: 'Qué determina el presupuesto de una plataforma SaaS y cómo comparar propuestas de desarrollo sin dejar fuera operación, seguridad y evolución.', image: '/images/resource-saas-planning.png', imageAlt: 'Módulos de un producto SaaS organizados sobre una mesa de planificación', readingTime: '8 min de lectura', updated: '2026-09-02', relatedService: { label: 'Solicitar alcance para un SaaS', href: '/desarrollo-saas' }, sections: [
    { title: 'No existe un precio único para un SaaS', paragraphs: ['El coste depende menos del número de pantallas que de las reglas, los perfiles de usuario, los datos y las integraciones que debe coordinar el producto.', 'Una estimación responsable empieza con un recorrido concreto y declara sus supuestos. Dar una cifra cerrada sin entender quién usa el sistema, qué información maneja y cómo se operará suele trasladar el coste a cambios posteriores.'], points: ['Roles y permisos', 'Complejidad de los flujos', 'Pagos y facturación', 'Integraciones externas', 'Migración de datos', 'Requisitos de seguridad'] },
    { title: 'Las partidas que debe incluir una propuesta', paragraphs: ['El presupuesto debería separar descubrimiento, experiencia de usuario, desarrollo, pruebas y puesta en producción. También debe explicar qué ocurre con administración, soporte e incidencias.', 'Esta separación permite recortar alcance sin recortar a ciegas la calidad del producto.'], points: ['Definición funcional y técnica', 'Diseño UX/UI', 'Aplicación y panel de administración', 'Pruebas y despliegue', 'Documentación y transferencia'] },
    { title: 'Costes recurrentes después del lanzamiento', paragraphs: ['Alojamiento, correo transaccional, almacenamiento, observabilidad y proveedores de pago pueden tener planes gratuitos al inicio, pero deben modelarse para el volumen esperado.', 'También hay que reservar capacidad para mantenimiento, seguridad y aprendizaje. Lanzar no elimina la incertidumbre: cambia las preguntas por datos reales.'] },
    { title: 'Cómo reducir inversión sin crear una deuda', paragraphs: ['La forma más segura de ajustar presupuesto es reducir casos de uso, perfiles e integraciones en la primera versión. Recortar autenticación, control de datos o pruebas crea un ahorro aparente.', 'Un alcance pequeño que resuelve una tarea completa suele aportar más información que una plataforma amplia con recorridos incompletos.'] },
    { title: 'Cómo comparar dos presupuestos', paragraphs: ['Compara entregables, exclusiones, propiedad del código, costes recurrentes y criterio de aceptación; no solo la cifra final.', 'La mejor propuesta es la que hace visibles los riesgos y permite entender qué decisión podrás tomar después del lanzamiento.'] },
  ] },
  'precio-desarrollo-mvp': { slug: 'precio-desarrollo-mvp', category: 'MVP y presupuesto', title: 'Precio de desarrollar un MVP: cómo estimar la primera versión', description: 'Una guía para calcular el presupuesto de un MVP según su alcance, integraciones, diseño y objetivo de validación.', image: '/images/resource-mvp-scope.png', imageAlt: 'Piezas seleccionadas para definir el alcance y presupuesto de un MVP', readingTime: '7 min de lectura', updated: '2026-09-02', relatedService: { label: 'Definir el presupuesto de un MVP', href: '/desarrollo-mvp' }, sections: [
    { title: 'El objetivo de validación define el presupuesto', paragraphs: ['No cuesta lo mismo validar interés mediante un flujo asistido que lanzar una aplicación capaz de cobrar, gestionar usuarios y operar sin intervención manual.', 'Antes de estimar, decide qué evidencia necesitas: uso, disposición a pagar, viabilidad técnica o capacidad operativa. El MVP debe financiar esa respuesta, no todas las ideas futuras.'] },
    { title: 'Qué elementos aumentan el coste', paragraphs: ['Los mayores cambios de esfuerzo suelen venir de las integraciones, los permisos, la calidad de los datos y las excepciones del proceso.', 'Una función aparentemente sencilla puede depender de proveedores, regulación o estados que no aparecen en la interfaz.'], points: ['Varios perfiles de usuario', 'Pagos o suscripciones', 'Aplicación móvil además de web', 'Migración de información', 'Integraciones con sistemas existentes', 'Requisitos legales o sectoriales'] },
    { title: 'Prototipo, MVP y producto inicial no son lo mismo', paragraphs: ['Un prototipo valida comprensión y navegación, pero no ejecuta la operación. Un MVP funcional permite completar el recorrido principal y obtener comportamiento real.', 'Aclarar qué se está presupuestando evita comparar una demostración visual con una aplicación preparada para usuarios.'] },
    { title: 'Cómo preparar una estimación útil', paragraphs: ['Reúne el usuario objetivo, el problema, el recorrido principal, las herramientas que deben conectarse y el plazo deseado. Añade ejemplos de datos y excepciones frecuentes.', 'Con ese contexto se puede plantear una horquilla inicial y después cerrar alcance, entregables y calendario.'] },
    { title: 'Qué debe quedar por escrito', paragraphs: ['La propuesta debe indicar qué incluye, qué queda fuera, cómo se aceptará cada entrega y quién será propietario del código y los diseños.', 'También conviene separar el coste de construcción de los servicios mensuales y de la evolución posterior.'] },
  ] },
  'ejemplos-automatizacion-ia-empresas': { slug: 'ejemplos-automatizacion-ia-empresas', category: 'IA aplicada', title: 'Automatización con IA para empresas: ejemplos y criterios de rentabilidad', description: 'Ejemplos de procesos empresariales que pueden automatizarse con IA y una forma práctica de priorizarlos por impacto, riesgo y viabilidad.', image: '/images/resource-ai-automation.png', imageAlt: 'Flujo empresarial automatizado que procesa información mediante inteligencia artificial', readingTime: '8 min de lectura', updated: '2026-09-02', relatedService: { label: 'Analizar un proceso para automatizar', href: '/automatizacion-ia' }, sections: [
    { title: 'Documentos y extracción de información', paragraphs: ['Facturas, contratos, formularios y correos pueden clasificarse y convertir sus datos en registros estructurados. El ahorro aparece cuando el volumen es frecuente y el equipo revisa hoy la misma información de forma repetitiva.', 'La automatización debe conservar el documento original, señalar los campos dudosos y enviar las excepciones a una persona.'] },
    { title: 'Atención y preparación de respuestas', paragraphs: ['La IA puede localizar información, resumir el contexto y proponer una respuesta para que el equipo la valide. Esto reduce el tiempo de búsqueda sin delegar automáticamente compromisos sensibles.', 'El caso mejora cuando existe una base de conocimiento mantenida y se registra qué fuentes sustentan cada propuesta.'] },
    { title: 'Clasificación y priorización comercial', paragraphs: ['Solicitudes, oportunidades y conversaciones pueden ordenarse según criterios definidos por el negocio. El sistema puede completar el contexto y recomendar el siguiente paso.', 'No debe sustituir sin control decisiones que afecten derechos o produzcan discriminación. El objetivo inicial es ayudar a priorizar, no ocultar el criterio.'] },
    { title: 'Informes y seguimiento operativo', paragraphs: ['Cuando un informe combina datos de varias herramientas y sigue una estructura estable, es posible automatizar la recopilación, detectar desviaciones y redactar un primer resumen.', 'Los indicadores y cálculos deben mantenerse como reglas verificables; la IA resulta útil para interpretar y explicar el contexto.'] },
    { title: 'Cómo saber si un caso será rentable', paragraphs: ['Calcula frecuencia, minutos actuales, coste del error, porcentaje de excepciones y tiempo de revisión. Después compara el proceso completo, no solo la velocidad del modelo.', 'Un buen primer proyecto es acotado, medible, reversible y suficientemente frecuente para aprender pronto.'], points: ['Volumen mensual', 'Tiempo manual por caso', 'Tasa de excepciones', 'Calidad de los datos', 'Riesgo de una respuesta incorrecta', 'Ahorro neto después de supervisión'] },
  ] },
}
