import type { ServiceContent } from '@/components/marketing/ServiceLanding'

export const serviceContent: Record<string, ServiceContent> = {
  'desarrollo-saas': {
    slug: 'desarrollo-saas', eyebrow: 'Desarrollo SaaS a medida', title: 'Desarrollo SaaS a medida para operar y crecer sin depender de parches.',
    intro: 'Diseñamos y construimos aplicaciones web por suscripción, plataformas B2B y herramientas especializadas adaptadas al modelo de negocio.',
    definition: 'Un SaaS a medida convierte un proceso o conocimiento propio en un producto accesible desde la web, con usuarios, permisos, datos, pagos e integraciones preparados para evolucionar.',
    situations: ['Tienes una idea validada y necesitas convertirla en un producto funcional.', 'Tu negocio depende de hojas de cálculo, herramientas desconectadas o tareas manuales.', 'El software estándar obliga a adaptar la operación en lugar de ayudarla.', 'Necesitas vender acceso recurrente a una herramienta, servicio o base de conocimiento.'],
    deliverables: [{ title: 'Arquitectura de producto', text: 'Definimos usuarios, permisos, datos, flujos e integraciones antes de escribir código.' }, { title: 'Experiencia y aplicación', text: 'Diseñamos y desarrollamos la interfaz completa para escritorio y móvil.' }, { title: 'Operación segura', text: 'Incluimos autenticación, control de acceso, copias, despliegue y observabilidad.' }, { title: 'Base para crecer', text: 'Documentamos el sistema y priorizamos la evolución a partir del uso real.' }],
    process: [{ title: 'Descubrimiento', text: 'Aterrizamos el problema, los usuarios, el modelo de negocio y las restricciones.' }, { title: 'Alcance del MVP', text: 'Separamos lo imprescindible de lo que puede esperar y cerramos un plan verificable.' }, { title: 'Diseño y desarrollo', text: 'Construimos en ciclos cortos con revisiones frecuentes sobre producto funcional.' }, { title: 'Lanzamiento', text: 'Desplegamos, medimos el uso y preparamos las siguientes decisiones.' }],
    decisions: [{ question: '¿Cuánto cuesta desarrollar un SaaS?', answer: 'Depende del número de roles, flujos e integraciones. Tras el diagnóstico preparamos un alcance cerrado con inversión y calendario.' }, { question: '¿Es obligatorio empezar con todas las funciones?', answer: 'No. Un primer lanzamiento debe resolver una tarea importante de principio a fin. El resto se prioriza con evidencia.' }, { question: '¿El código será de mi empresa?', answer: 'Sí. El proyecto, el código y la documentación se entregan al cliente según las condiciones acordadas.' }],
    related: [{ label: 'Desarrollo de MVP', href: '/desarrollo-mvp' }, { label: 'Software empresarial', href: '/software-empresarial' }],
  },
  'automatizacion-ia': {
    slug: 'automatizacion-ia', eyebrow: 'Automatización con IA', title: 'Automatización de procesos con IA donde realmente ahorra trabajo.',
    intro: 'Analizamos tareas repetitivas, documentos y decisiones operativas para automatizar solo los pasos que aportan un retorno claro.',
    definition: 'Automatizar con IA no consiste en añadir un chatbot. Consiste en conectar información, reglas y revisión humana para reducir tiempos sin perder control.',
    situations: ['El equipo copia información entre correos, documentos y aplicaciones.', 'Clasificar, resumir o revisar documentos consume horas cada semana.', 'Las respuestas dependen de buscar información dispersa y repetir criterios.', 'Quieres probar IA con un caso acotado antes de desplegarla en toda la empresa.'],
    deliverables: [{ title: 'Mapa del proceso', text: 'Medimos pasos, frecuencia, excepciones y coste actual para encontrar el punto de mayor impacto.' }, { title: 'Prototipo controlado', text: 'Probamos el flujo con datos representativos y criterios de aceptación claros.' }, { title: 'Automatización integrada', text: 'Conectamos modelos, reglas, aplicaciones y revisión humana dentro de la operación.' }, { title: 'Control y seguimiento', text: 'Registramos resultados, errores y costes para poder mejorar el sistema.' }],
    process: [{ title: 'Auditoría', text: 'Elegimos un proceso frecuente, estable y medible.' }, { title: 'Prueba', text: 'Validamos precisión, tiempo y coste con ejemplos reales.' }, { title: 'Integración', text: 'Incorporamos la automatización a las herramientas existentes.' }, { title: 'Supervisión', text: 'Definimos revisión humana, alertas y evolución.' }],
    decisions: [{ question: '¿La IA puede equivocarse?', answer: 'Sí. Por eso diseñamos límites, validaciones y revisión humana según el riesgo de cada decisión.' }, { question: '¿Hace falta cambiar todas nuestras herramientas?', answer: 'Normalmente no. Priorizamos integraciones con los sistemas que el equipo ya utiliza.' }, { question: '¿Cómo se protege la información?', answer: 'Se define qué datos puede procesar cada servicio, dónde se almacenan y durante cuánto tiempo.' }],
    related: [{ label: 'Software empresarial', href: '/software-empresarial' }, { label: 'Desarrollo SaaS', href: '/desarrollo-saas' }],
  },
  'desarrollo-mvp': {
    slug: 'desarrollo-mvp', eyebrow: 'Desarrollo de MVP', title: 'Un MVP para aprender del mercado sin construir de más.',
    intro: 'Convertimos una hipótesis de negocio en una primera versión utilizable, con el alcance necesario para probar adopción y operación.',
    definition: 'Un MVP no es una demo incompleta. Es la versión más pequeña que permite a un usuario real resolver el problema principal y al negocio aprender de su comportamiento.',
    situations: ['Necesitas comprobar si alguien utilizará o pagará por la solución.', 'Buscas presentar un producto funcional a clientes, socios o inversión.', 'El alcance crece cada semana y necesitas fijar una primera versión.', 'Quieres sustituir un prototipo sin futuro por una base técnica mantenible.'],
    deliverables: [{ title: 'Hipótesis y alcance', text: 'Definimos qué debe demostrar el lanzamiento y qué métricas lo confirmarán.' }, { title: 'Prototipo navegable', text: 'Validamos el flujo y el lenguaje antes de concentrar inversión en desarrollo.' }, { title: 'MVP funcional', text: 'Construimos el recorrido principal, administración y conexiones imprescindibles.' }, { title: 'Plan posterior', text: 'Ordenamos mejoras a partir del uso, las incidencias y las conversaciones con clientes.' }],
    process: [{ title: 'Enfoque', text: 'Elegimos usuario, problema e hipótesis principal.' }, { title: 'Recorte', text: 'Quitamos funciones que no son necesarias para aprender.' }, { title: 'Construcción', text: 'Diseñamos y desarrollamos una versión lista para usuarios.' }, { title: 'Aprendizaje', text: 'Medimos, entrevistamos y decidimos la siguiente inversión.' }],
    decisions: [{ question: '¿Cuánto tarda un MVP?', answer: 'Un alcance bien acotado suele requerir entre 4 y 8 semanas. Las integraciones y los requisitos regulatorios pueden ampliar el plazo.' }, { question: '¿El MVP se tendrá que rehacer?', answer: 'No debería. Elegimos una base proporcional al riesgo, pero preparada para evolucionar si la hipótesis funciona.' }, { question: '¿Qué se queda fuera?', answer: 'Todo lo que no sea necesario para completar el flujo principal, operar el servicio o medir el aprendizaje.' }],
    related: [{ label: 'Desarrollo SaaS', href: '/desarrollo-saas' }, { label: 'Automatización con IA', href: '/automatizacion-ia' }],
  },
  'software-empresarial': {
    slug: 'software-empresarial', eyebrow: 'Software empresarial', title: 'Herramientas internas diseñadas alrededor de cómo trabaja tu empresa.',
    intro: 'Centralizamos operaciones, clientes, documentos y seguimiento en aplicaciones web que eliminan duplicidades y hacen visible el trabajo.',
    definition: 'El software empresarial a medida reúne procesos que hoy viven en hojas de cálculo, correos y aplicaciones aisladas, manteniendo las reglas que hacen diferente a la empresa.',
    situations: ['La información se duplica y nadie sabe cuál es la versión correcta.', 'El equipo pierde tiempo preparando informes o actualizando varios sistemas.', 'El CRM o ERP actual no refleja el flujo real de trabajo.', 'Clientes o colaboradores necesitan consultar información sin depender del equipo.'],
    deliverables: [{ title: 'Modelo operativo', text: 'Traducimos responsabilidades, estados y excepciones a un flujo compartido.' }, { title: 'Paneles por función', text: 'Cada persona ve las tareas, datos y acciones que necesita.' }, { title: 'Integraciones', text: 'Conectamos correo, documentos, facturación, CRM o servicios externos.' }, { title: 'Adopción', text: 'Preparamos migración, permisos, documentación y acompañamiento inicial.' }],
    process: [{ title: 'Observación', text: 'Entendemos cómo se realiza el trabajo, incluidas las excepciones.' }, { title: 'Simplificación', text: 'Eliminamos pasos innecesarios antes de automatizarlos.' }, { title: 'Implantación', text: 'Desarrollamos por áreas sin detener la operación.' }, { title: 'Mejora', text: 'Medimos adopción, tiempos e incidencias para priorizar.' }],
    decisions: [{ question: '¿Es mejor adaptar una herramienta existente?', answer: 'A veces sí. Comparamos coste, encaje, dependencia y mantenimiento antes de recomendar desarrollo a medida.' }, { question: '¿Cómo se migra la información?', answer: 'Auditamos origen, calidad y relaciones de los datos antes de planificar una migración verificable.' }, { question: '¿Puede crecer por módulos?', answer: 'Sí. Diseñamos límites claros para incorporar áreas sin rehacer el sistema completo.' }],
    related: [{ label: 'Automatización con IA', href: '/automatizacion-ia' }, { label: 'Desarrollo SaaS', href: '/desarrollo-saas' }],
  },
}
